name: SSL certificate test

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
    branches:
      - master
  pull_request:
    paths:
      - "**.py"
      - "**.yml"
  workflow_dispatch:

jobs:
  ssl_cert:
    strategy:
      fail-fast: false
      matrix:
        include:
          - exasol-tag: 7.1.3

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ./pyexasol

      - name: Checkout test environment
        uses: actions/checkout@v2
        with:
          repository: exasol/integration-test-docker-environment
          path: './test_env'

      - name: Spawn EXASOL environemnt
        run: ./start-test-env spawn-test-environment --environment-name ssl --docker-db-image-version=${{ matrix.exasol-tag }} --database-port-forward 8888 --create-certificates
        working-directory: ./test_env

      - name: Copy current pyexasol into test container
        run: docker cp ./pyexasol test_container_ssl:/tmp

      - name: Install python, pip, current pyexasol inside test container
        run: docker exec -t test_container_ssl bash "apt-get -y update && apt-get -y install python3 python3-pip && pip3 install pandas && pip3 install -e /tmp/pyexasol"

      - name: Run test
        run: docker exec -t test_container_ssl python3 "/tmp/pyexasol/examples/_ssl_test.py"
