name: SSL certificate test

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
    branches:
      - master
  pull_request:
    paths:
      - "**.py"
      - "**.yml"
  workflow_dispatch:

jobs:
  ssl_cert:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.9
            exasol-tag: 7.1.3

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .[pandas]

      - name: Checkout test environment
        uses: actions/checkout@v2
        with:
          repository: exasol/integration-test-docker-environment
          path: './test_env'

      - name: Spawn EXASOL environemnt
        run: ./start-test-env spawn-test-environment --environment-name ssl --docker-db-image-version=${{ matrix.exasol-tag }} --database-port-forward 8888 --create-certificates
        working-directory: ./test_env

      - name: Pull certificate from container
        run: docker cp test_container_ssl:/certificates/rootCA.crt .

      - name: Setup custom host
        run: echo "127.0.0.1 exasol-test-database" | sudo tee -a /etc/hosts

      - name: Run test
        run: python examples/_ssl_test.py
